### PR TITLE
Adding photos

### PR DESCRIPTION
**Pull request by riverma**
- Added photos from Google Docs pages
- Reorganized folder structure of img/ directory to make it less messy.

### CODE REVIEW

**Comment by csseu** [comment]
Looks good to me!

**Comment by ruqpyL2** [comment]
Looks good to me!

**Review by csseu — APPROVED** [review]
This is the feature you want me to use, right?

**Comment by riverma** [comment]
Yes - thanks for the fast review! Confirmed and merged.

**Pull request merged**
